name: Build

on:
    push: ~
    pull_request: ~
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday
    workflow_dispatch: ~

jobs:
    tests:
        runs-on: ubuntu-latest
        name: "PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, Twig ${{ matrix.twig }}"
        strategy:
            fail-fast: false
            matrix:
                php: ["8.0", "8.1"]
                symfony: ["5.4.*", "6.0.*"]
                twig: ["^2.12", "^3.3"]

        steps:
            -
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -
                name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer global require --no-progress --no-scripts --no-plugins "symfony/flex:^1.10"
                    composer config extra.symfony.require "${{ matrix.symfony }}"
                    (cd src/Component && composer config extra.symfony.require "${{ matrix.symfony }}")

            -
                name: Restrict Twig version
                if: matrix.twig != ''
                run: |
                    composer require "twig/twig:${{ matrix.twig }}" --no-update --no-scripts

            -
                name: Remove Swiftmailer on Symfony >= 6
                if: ${{ true != contains( matrix.symfony, '5.4.*' ) }}
                run: |
                    composer remove --dev symfony/swiftmailer-bundle  --no-update --no-scripts

            -
                name: Install dependencies
                run: |
                    composer update ${{ matrix.composer-flags }} --no-scripts
                    (cd src/Component && composer update ${{ matrix.composer-flags }} --no-scripts)

            -
                name: Run analysis
                run: |
                    composer analyse
                    (cd src/Component && composer validate --strict)

            -
                name: Run component tests
                run: (cd src/Component && vendor/bin/phpspec run)

            -
                name: Run PHPSpec tests
                run: vendor/bin/phpspec run

            -
                name: Test bundle (with all services)
                run: |
                    rm -rf src/Bundle/test/var/cache
                    composer require symfony/mailer --no-interaction --no-scripts
                    composer require symfony/swiftmailer-bundle --no-interaction --no-scripts
                    (cd src/Bundle/test && APP_ENV=test bin/console lint:container)

            -
                name: Test bundle (with Swift Mailer)
                if: ${{ true == contains( matrix.symfony, '5.4.*' ) }}
                run: |
                    rm -rf src/Bundle/test/var/cache
                    composer remove symfony/mailer --no-scripts
                    (cd src/Bundle/test && APP_ENV=test_with_swiftmailer bin/console lint:container)
                    vendor/bin/phpunit src/Bundle/tests/Functional/SwiftmailerSenderTest.php

            -
                name: Test bundle (with SymfonyMailer)
                run: |
                    rm -rf src/Bundle/test/var/cache
                    composer remove symfony/swiftmailer-bundle --no-scripts
                    composer require symfony/mailer --no-scripts
                    (cd src/Bundle/test && APP_ENV=test_with_symfony_mailer bin/console lint:container)
                    vendor/bin/phpunit src/Bundle/tests/Functional/SymfonyMailerSenderTest.php

            -
                name: Run lint container (with no mailers)
                run: |
                    rm -rf src/Bundle/test/var/cache
                    composer remove symfony/mailer --no-scripts
                    (cd src/Bundle/test && APP_ENV=test_no_mailers bin/console lint:container)
